### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by skwde** [joshbolduc/vscode-commitlint#784]
Something similar is already mentioned here https://github.com/joshbolduc/vscode-commitlint/issues/744 / https://github.com/joshbolduc/vscode-commitlint/issues/750.

I now have `commitlint` installed via a conda installed node (inside a container). I can use it without issues on the command line.

Following modules are installed

```sh
(base) root@213d29790eb9:/workspaces/docs# npm list -g
/opt/conda/lib
├── @commitlint/cli@19.2.1
├── @commitlint/config-conventional@19.1.0
├── corepack@0.20.0
└── npm@10.1.0
```

I have following `commitlint.config.js` in my project directory:

```js
module.exports = {
    extends: ['@commitlint/config-conventional'],
};
```

and following `commitlint` related VSCode settings

```json
    "commitlint.log.enabled": true,
    "commitlint.globalLibraryPath": "/opt/conda/lib",
    "commitlint.globalNodePath": "/opt/conda/bin/node",
```

playing with `globalLibraryPath` or setting `preferBundledLibraries` to `true` does not help and lead to the same problem.

**Comment by joshbolduc** [comment]
There may be multiple factors at play here, but I'd bet #753 is at least partly to blame. You could give `18.x` a try in the meantime and see if that works.

**Comment by skwde** [comment]
Using `@commitlint/config-conventional@18`, i.e.

```out
/opt/conda/lib
├── @commitlint/cli@19.2.1
├── @commitlint/config-conventional@18.6.3
├── corepack@0.20.0
└── npm@10.1.0
```

as you suggested indeed works, even without setting the path explicitly.

Note, when installing the package better reload the VSCode window.

**Comment by joshbolduc** [comment]
Reopening since #753 [didn't fix this](https://github.com/joshbolduc/vscode-commitlint/issues/753#issuecomment-2071356336) per @skwde:

> @joshbolduc, I hate to bring the bad news, but it still seems broken for v19. #784 still doesn't work with extension version 2.6.0
> 
> ```shell
> # npm list -g
> /opt/conda/lib
> ├── @commitlint/cli@19.3.0
> ├── @commitlint/config-conventional@19.2.2
> ```
> 
> And the extension output:
> 
> ```
> loading @commitlint/parse dynamically via /opt/conda/lib/node_modules/@commitlint/cli/node_modules/@commitlint/parse/lib/index.js
> loading @commitlint/load dynamically via /opt/conda/lib/node_modules/@commitlint/cli/node_modules/@commitlint/load/lib/load.js
> loading @commitlint/lint dynamically via /opt/conda/lib/node_modules/@commitlint/cli/node_modules/@commitlint/lint/lib/lint.js
> Load config error stack:
> Error: Cannot find module "@commitlint/config-conventional" from "/workspaces/docs"
> ```
> 
> The downgrade to v18.6.3 still works.

I haven't had a chance to investigate further and see what might have changed here in v19.

**Comment by skwde** [comment]
Can we have a new take on this. I now tried @18 / @19 and @20 of `@commitlint`.

As before, at most I get `@commitlint/cli` to be found.
It seems that `@commitlint/config-conventional` is never detected, even installed next to `cli`, i.e. via

```sh
npm install -g @commitlint/cli @commitlint/config-conventional
```

I always get

```out
Error: Cannot find module "@commitlint/config-conventional" from <project root, e.g devcontainer workspace>
```

I only used `commitlint.globalLibraryPath` (other settings didn't help).

**Comment by skwde** [comment]
I seems like `commitlint` does not search for `@commitlint/config-conventional` but only looks in the local project folder.

In fact, a workaround is to symlink `node_modules` to the local workspace folder.

In addition, I can run

```sh
git log -1 --pretty=%B | /home/stefan/.pixi/envs/nodejs/bin/commitlint --config commitlint.config.js 
```

which works without problems, suggesting that the problem is within the extension?

**Comment by joshbolduc** [comment]
Sorry that it's not working for you. Can you shed some more light on your environment? I've been toying with getting some basic smoke tests running in CI against various configurations, but I'm not familiar with conda and so far haven't been able to consistently reproduce these types of failures.

IIRC the basic problem is the extension uses VS Code's copy of node, not your system's (or any copy managed by a version manager), so it doesn't resolve globally installed modules the way you'd expect from running commitlint in your shell. And commitlint puts its own spin on module resolution when it comes to `extends`, which adds another variable. From the extension's POV it tries to induce the commitlint libraries to act as they would when invoked in the context of the CLI, but it's a bit opaque.

**Comment by skwde** [comment]
@joshbolduc thanks for your response.

What `conda` (and alternatives:`mamba` / `micromamba`) / `pixi` does is installing packages from dedicated channels like `conda-forge` in an isolated environment while resolving / ensuring compatibility.
(In a way like virtual environments in python but more general).

One of those packages provided via `conda-forge` is `nodejs` which ships `npm`.

Once installed the environment can be activated and certain environment variables are set / adjusted (e.g. `PATH` / `CONDA_PREFIX` / ...).

```sh
npm install -g
```

then put packages under `$CONDA_PREFIX/...`, i.e. **node packages in non default locations**.

---

I do get the point of extensions using VSCode's node copy, but `commitlint` has the settings

```json
 "commitlint.globalLibraryPath": "/opt/conda/lib",
  "commitlint.globalNodePath": "/opt/conda/bin/node",
```

(as mentioned above)

Which seem to have no effect on the resolution of packages.

**Comment by skwde** [comment]
I just came back to this because I tried setup via `nvm`. Weirdly, only `@commitlin/config-conventional` is not detected...
In this scenario, no `conda`-like environments are involved. I guess this is a very typical setup for node dev?

Here are the version + what I installed

```sh
$ nvm --version
0.40.6
$ node --version
v24.18.0
$ npm --version
11.16.0
$ npm install -g @commitlint/config-conventional @commitlint/cli
```

Here is the output of the commitlint extension in VSCode:

```sh
loading @commitlint/parse dynamically via file:///usr/local/share/nvm/versions/node/v24.18.0/lib/node_modules/@commitlint/cli/node_modules/@commitlint/parse/lib/index.js
loading @commitlint/load dynamically via file:///usr/local/share/nvm/versions/node/v24.18.0/lib/node_modules/@commitlint/cli/node_modules/@commitlint/load/lib/load.js
loading @commitlint/lint dynamically via file:///usr/local/share/nvm/versions/node/v24.18.0/lib/node_modules/@commitlint/cli/node_modules/@commitlint/lint/lib/lint.js
Load config error stack:
Error: Cannot find module "@commitlint/config-conventional" from "/workspaces/services-mono"
```

`/workspaces/services-mono` is the VSCode devcontainer workspace folder.

Can you actually reproduce this issue?
